 const School=[
    {"id": 1, "name": "Phillips Exeter Academy", "city": "Exeter", "location": "New Hampshire", "rating": "4.8"},
    {"id": 2, "name": "Phillips Academy Andover", "city": "Andover", "location": "Massachusetts", "rating": "4.7"},
    {"id": 3, "name": "St. Mark's School of Texas", "city": "Dallas", "location": "Texas", "rating": "4.6"},
    {"id": 4, "name": "The Lawrenceville School", "city": "Lawrenceville", "location": "New Jersey", "rating": "4.5"},
    {"id": 5, "name": "Choate Rosemary Hall", "city": "Wallingford", "location": "Connecticut", "rating": "4.5"},
    {"id": 6, "name": "The Hotchkiss School", "city": "Lakeville", "location": "Connecticut", "rating": "4.4"},
    {"id": 7, "name": "Groton School", "city": "Groton", "location": "Massachusetts", "rating": "4.3"},
    {"id": 8, "name": "The Thacher School", "city": "Ojai", "location": "California", "rating": "4.3"},
    {"id": 9, "name": "Horace Mann School", "city": "New York City", "location": "New York", "rating": "4.2"},
    {"id": 10, "name": "Deerfield Academy", "city": "Deerfield", "location": "Massachusetts", "rating": "4.2"},
    {"id": 11, "name": "The Loomis Chaffee School", "city": "Windsor", "location": "Connecticut", "rating": "4.1"},
    {"id": 12, "name": "Middlesex School", "city": "Concord", "location": "Massachusetts", "rating": "4.1"},
    {"id": 13, "name": "The Harker School", "city": "San Jose", "location": "California", "rating": "4.1"},
    {"id": 14, "name": "Milton Academy", "city": "Milton", "location": "Massachusetts", "rating": "4.0"},
    {"id": 15, "name": "Trinity School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 16, "name": "The Roxbury Latin School", "city": "West Roxbury", "location": "Massachusetts", "rating": "4.0"},
    {"id": 17, "name": "Harvard-Westlake School", "city": "Los Angeles", "location": "California", "rating": "4.0"},
    {"id": 18, "name": "The Brearley School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 19, "name": "St. Paul's School", "city": "Concord", "location": "New Hampshire", "rating": "4.0"},
    {"id": 20, "name": "The Webb Schools", "city": "Claremont", "location": "California", "rating": "4.0"},
    {"id": 21, "name": "Sidwell Friends School", "city": "Washington", "location": "District of Columbia", "rating": "4.0"},
    {"id": 22, "name": "Buckingham Browne & Nichols", "city": "Cambridge", "location": "Massachusetts", "rating": "4.0"},
    {"id": 23, "name": "The Latin School of Chicago", "city": "Chicago", "location": "Illinois", "rating": "4.0"},
    {"id": 24, "name": "The Spence School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 25, "name": "Collegiate School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 26, "name": "The Chapin School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 27, "name": "Crystal Springs Uplands School", "city": "Hillsborough", "location": "California", "rating": "4.0"},
    {"id": 28, "name": "National Cathedral School", "city": "Washington", "location": "District of Columbia", "rating": "4.0"},
    {"id": 29, "name": "Polytechnic School", "city": "Pasadena", "location": "California", "rating": "4.0"},
    {"id": 30, "name": "The Westminster Schools", "city": "Atlanta", "location": "Georgia", "rating": "4.0"},
    {"id": 31, "name": "Germantown Friends School", "city": "Philadelphia", "location": "Pennsylvania", "rating": "4.0"},
    {"id": 32, "name": "The Pingry School", "city": "Basking Ridge", "location": "New Jersey", "rating": "4.0"},
    {"id": 33, "name": "Ethical Culture Fieldston School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 34, "name": "The Potomac School", "city": "McLean", "location": "Virginia", "rating": "4.0"},
    {"id": 35, "name": "Head-Royce School", "city": "Oakland", "location": "California", "rating": "4.0"},
    {"id": 36, "name": "The Masters School", "city": "Dobbs Ferry", "location": "New York", "rating": "4.0"},
    {"id": 37, "name": "Ransom Everglades School", "city": "Miami", "location": "Florida", "rating": "4.0"},
    {"id": 38, "name": "Riverdale Country School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 39, "name": "Greens Farms Academy", "city": "Westport", "location": "Connecticut", "rating": "4.0"},
    {"id": 40, "name": "The Blake School", "city": "Minneapolis", "location": "Minnesota", "rating": "4.0"},
    {"id": 41, "name": "The Lovett School", "city": "Atlanta", "location": "Georgia", "rating": "4.0"},
    {"id": 42, "name": "The Bishop's School", "city": "La Jolla", "location": "California", "rating": "4.0"},
    {"id": 43, "name": "Hackley School", "city": "Tarrytown", "location": "New York", "rating": "4.0"},
    {"id": 44, "name": "The Dalton School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 45, "name": "Lakeside School", "city": "Seattle", "location": "Washington", "rating": "4.0"},
    {"id": 46, "name": "The Athenian School", "city": "Danville", "location": "California", "rating": "4.0"},
    {"id": 47, "name": "Kent School", "city": "Kent", "location": "Connecticut", "rating": "4.0"},
    {"id": 48, "name": "Marlborough School", "city": "Los Angeles", "location": "California", "rating": "4.0"},
    {"id": 49, "name": "Emma Willard School", "city": "Troy", "location": "New York", "rating": "4.0"},
    {"id": 50, "name": "St. John's School", "city": "Houston", "location": "Texas", "rating": "4.0"},
    {"id": 51, "name": "Hathaway Brown School", "city": "Shaker Heights", "location": "Ohio", "rating": "4.0"},
    {"id": 52, "name": "The Hewitt School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 53, "name": "The Wheeler School", "city": "Providence", "location": "Rhode Island", "rating": "4.0"},
    {"id": 54, "name": "The Green Vale School", "city": "Old Brookville", "location": "New York", "rating": "4.0"},
    {"id": 55, "name": "Riverdale Country School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 56, "name": "Martha's Vineyard Regional High School", "city": "Oak Bluffs", "location": "Massachusetts", "rating": "4.0"},
    {"id": 57, "name": "The Putney School", "city": "Putney", "location": "Vermont", "rating": "4.0"},
    {"id": 58, "name": "The Brearley School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 59, "name": "Montclair Kimberley Academy", "city": "Montclair", "location": "New Jersey", "rating": "4.0"},
    {"id": 60, "name": "Spence School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 61, "name": "Saint Ann's School", "city": "Brooklyn", "location": "New York", "rating": "4.0"},
    {"id": 62, "name": "The Dalton School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 63, "name": "The Madeira School", "city": "McLean", "location": "Virginia", "rating": "4.0"},
    {"id": 64, "name": "Northfield Mount Hermon", "city": "Mount Hermon", "location": "Massachusetts", "rating": "4.0"},
    {"id": 65, "name": "Salisbury School", "city": "Salisbury", "location": "Connecticut", "rating": "4.0"},
    {"id": 66, "name": "Westminster School", "city": "Simsbury", "location": "Connecticut", "rating": "4.0"},
    {"id": 67, "name": "Episcopal High School", "city": "Alexandria", "location": "Virginia", "rating": "4.0"},
    {"id": 68, "name": "Asheville School", "city": "Asheville", "location": "North Carolina", "rating": "4.0"},
    {"id": 69, "name": "St. Andrew's School", "city": "Middletown", "location": "Delaware", "rating": "4.0"},
    {"id": 70, "name": "The Ethel Walker School", "city": "Simsbury", "location": "Connecticut", "rating": "4.0"},
    {"id": 71, "name": "Kimball Union Academy", "city": "Meriden", "location": "New Hampshire", "rating": "4.0"},
    {"id": 72, "name": "Concord Academy", "city": "Concord", "location": "Massachusetts", "rating": "4.0"},
    {"id": 73, "name": "Suffield Academy", "city": "Suffield", "location": "Connecticut", "rating": "4.0"},
    {"id": 74, "name": "Holderness School", "city": "Holderness", "location": "New Hampshire", "rating": "4.0"},
    {"id": 75, "name": "Berkshire School", "city": "Sheffield", "location": "Massachusetts", "rating": "4.0"},
    {"id": 76, "name": "Miss Porter's School", "city": "Farmington", "location": "Connecticut", "rating": "4.0"},
    {"id": 77, "name": "St. George's School", "city": "Middletown", "location": "Rhode Island", "rating": "4.0"},
    {"id": 78, "name": "Webb School of Knoxville", "city": "Knoxville", "location": "Tennessee", "rating": "4.0"},
    {"id": 79, "name": "The Gunnery", "city": "Washington", "location": "Connecticut", "rating": "4.0"},
    {"id": 80, "name": "Peddie School", "city": "Hightstown", "location": "New Jersey", "rating": "4.0"},
    {"id": 81, "name": "Pomfret School", "city": "Pomfret", "location": "Connecticut", "rating": "4.0"},
    {"id": 82, "name": "The Pennington School", "city": "Pennington", "location": "New Jersey", "rating": "4.0"},
    {"id": 83, "name": "Portsmouth Abbey School", "city": "Portsmouth", "location": "Rhode Island", "rating": "4.0"},
    {"id": 84, "name": "Foxcroft School", "city": "Middleburg", "location": "Virginia", "rating": "4.0"},
    {"id": 85, "name": "The Wardlaw-Hartridge School", "city": "Edison", "location": "New Jersey", "rating": "4.0"},
    {"id": 86, "name": "Milton Hershey School", "city": "Hershey", "location": "Pennsylvania", "rating": "4.0"},
    {"id": 87, "name": "The Tatnall School", "city": "Wilmington", "location": "Delaware", "rating": "4.0"},
    {"id": 88, "name": "The Hun School of Princeton", "city": "Princeton", "location": "New Jersey", "rating": "4.0"},
    {"id": 89, "name": "The Harvey School", "city": "Katonah", "location": "New York", "rating": "4.0"},
    {"id": 90, "name": "Storm King School", "city": "Cornwall-on-Hudson", "location": "New York", "rating": "4.0"},
    {"id": 91, "name": "Oakwood Friends School", "city": "Poughkeepsie", "location": "New York", "rating": "4.0"},
    {"id": 92, "name": "Emmaus Christian Academy", "city": "Richmond", "location": "Virginia", "rating": "4.0"},
    {"id": 93, "name": "Newton Country Day School", "city": "Newton", "location": "Massachusetts", "rating": "4.0"},
    {"id": 94, "name": "Dana Hall School", "city": "Wellesley", "location": "Massachusetts", "rating": "4.0"},
    {"id": 95, "name": "The Cambridge School of Weston", "city": "Weston", "location": "Massachusetts", "rating": "4.0"},
    {"id": 96, "name": "Belmont Hill School", "city": "Belmont", "location": "Massachusetts", "rating": "4.0"},
    {"id": 97, "name": "St. Sebastian's School", "city": "Needham", "location": "Massachusetts", "rating": "4.0"},
    {"id": 98, "name": "Winsor School", "city": "Boston", "location": "Massachusetts", "rating": "4.0"},
    {"id": 99, "name": "Concord-Carlisle High School", "city": "Concord", "location": "Massachusetts", "rating": "4.0"},
    {"id": 100, "name": "St. Stephen's Episcopal School", "city": "Austin", "location": "Texas", "rating": "4.0"},
    {"id": 101, "name": "Cranbrook Schools", "city": "Bloomfield Hills", "location": "Michigan", "rating": "4.0"},
    {"id": 102, "name": "University of Chicago Laboratory Schools", "city": "Chicago", "location": "Illinois", "rating": "4.0"},
    {"id": 103, "name": "The Miami Valley School", "city": "Dayton", "location": "Ohio", "rating": "4.0"},
    {"id": 104, "name": "Carolina Day School", "city": "Asheville", "location": "North Carolina", "rating": "4.0"},
    {"id": 105, "name": "The Packer Collegiate Institute", "city": "Brooklyn", "location": "New York", "rating": "4.0"},
    {"id": 106, "name": "Friends Seminary", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 107, "name": "The Brearley School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 108, "name": "Ethical Culture Fieldston School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 109, "name": "The Brearley School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 110, "name": "Riverdale Country School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 111, "name": "The Chapin School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 112, "name": "Trinity School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 113, "name": "Horace Mann School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 114, "name": "The Spence School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 115, "name": "The Dalton School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 116, "name": "The Chapin School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 117, "name": "Collegiate School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 118, "name": "Friends Seminary", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 119, "name": "Poly Prep Country Day School", "city": "Brooklyn", "location": "New York", "rating": "4.0"},
    {"id": 120, "name": "The Brearley School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 121, "name": "The Spence School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 122, "name": "Trinity School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 123, "name": "Horace Mann School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 124, "name": "Collegiate School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 125, "name": "The Dalton School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 126, "name": "Ethical Culture Fieldston School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 127, "name": "Riverdale Country School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 128, "name": "The Chapin School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 129, "name": "Friends Seminary", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 130, "name": "The Spence School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 131, "name": "Poly Prep Country Day School", "city": "Brooklyn", "location": "New York", "rating": "4.0"},
    {"id": 132, "name": "Ethical Culture Fieldston School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 133, "name": "Riverdale Country School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 134, "name": "Friends Seminary", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 135, "name": "The Brearley School", "city": "New York City", "location": "New York", "rating": "4.0"},
    {"id": 136, "name": "Canterbury School", "city": "New Milford", "location": "Connecticut", "rating": "3.8"},
    {"id": 137, "name": "The Gunnery School", "city": "Washington", "location": "Connecticut", "rating": "3.8"},
    {"id": 138, "name": "The Madeira School", "city": "McLean", "location": "Virginia", "rating": "3.7"},
    {"id": 139, "name": "Proctor Academy", "city": "Andover", "location": "New Hampshire", "rating": "3.7"},
    {"id": 140, "name": "St. Timothy's School", "city": "Stevenson", "location": "Maryland", "rating": "3.6"},
    {"id": 141, "name": "Hebron Academy", "city": "Hebron", "location": "Maine", "rating": "3.6"},
    {"id": 142, "name": "Sandy Spring Friends School", "city": "Sandy Spring", "location": "Maryland", "rating": "3.5"},
    {"id": 143, "name": "Worcester Academy", "city": "Worcester", "location": "Massachusetts", "rating": "3.5"},
    {"id": 144, "name": "Gould Academy", "city": "Bethel", "location": "Maine", "rating": "3.4"},
    {"id": 145, "name": "Vermont Academy", "city": "Saxtons River", "location": "Vermont", "rating": "3.4"}
] 

const College=[
    {"id": 1, "name": "Harvard University", "city": "Cambridge", "location": "Massachusetts", "rating": "4.8"},
    {"id": 2, "name": "Stanford University", "city": "Stanford", "location": "California", "rating": "4.8"},
    {"id": 3, "name": "Massachusetts Institute of Technology", "city": "Cambridge", "location": "Massachusetts", "rating": "4.9"},
    {"id": 4, "name": "California Institute of Technology", "city": "Pasadena", "location": "California", "rating": "4.8"},
    {"id": 5, "name": "University of Chicago", "city": "Chicago", "location": "Illinois", "rating": "4.7"},
    {"id": 6, "name": "Princeton University", "city": "Princeton", "location": "New Jersey", "rating": "4.8"},
    {"id": 7, "name": "Columbia University", "city": "New York City", "location": "New York", "rating": "4.7"},
    {"id": 8, "name": "Yale University", "city": "New Haven", "location": "Connecticut", "rating": "4.7"},
    {"id": 9, "name": "University of Pennsylvania", "city": "Philadelphia", "location": "Pennsylvania", "rating": "4.6"},
    {"id": 10, "name": "Duke University", "city": "Durham", "location": "North Carolina", "rating": "4.6"},
    {"id": 11, "name": "University of California, Berkeley", "city": "Berkeley", "location": "California", "rating": "4.5"},
    {"id": 12, "name": "University of California, Los Angeles", "city": "Los Angeles", "location": "California", "rating": "4.5"},
    {"id": 13, "name": "University of Michigan", "city": "Ann Arbor", "location": "Michigan", "rating": "4.5"},
    {"id": 14, "name": "University of Virginia", "city": "Charlottesville", "location": "Virginia", "rating": "4.5"},
    {"id": 15, "name": "University of California, San Diego", "city": "La Jolla", "location": "California", "rating": "4.4"},
    {"id": 16, "name": "University of California, Santa Barbara", "city": "Santa Barbara", "location": "California", "rating": "4.4"},
    {"id": 17, "name": "University of California, Irvine", "city": "Irvine", "location": "California", "rating": "4.4"},
    {"id": 18, "name": "University of Southern California", "city": "Los Angeles", "location": "California", "rating": "4.4"},
    {"id": 19, "name": "Northwestern University", "city": "Evanston", "location": "Illinois", "rating": "4.5"},
    {"id": 20, "name": "University of Notre Dame", "city": "Notre Dame", "location": "Indiana", "rating": "4.4"},
    {"id": 21, "name": "Johns Hopkins University", "city": "Baltimore", "location": "Maryland", "rating": "4.5"},
    {"id": 22, "name": "University of Washington", "city": "Seattle", "location": "Washington", "rating": "4.3"},
    {"id": 23, "name": "University of California, Davis", "city": "Davis", "location": "California", "rating": "4.3"},
    {"id": 24, "name": "University of Wisconsin-Madison", "city": "Madison", "location": "Wisconsin", "rating": "4.3"},
    {"id": 25, "name": "University of Texas at Austin", "city": "Austin", "location": "Texas", "rating": "4.3"},
    {"id": 26, "name": "University of Illinois at Urbana-Champaign", "city": "Champaign", "location": "Illinois", "rating": "4.3"},
    {"id": 27, "name": "University of Florida", "city": "Gainesville", "location": "Florida", "rating": "4.2"},
    {"id": 28, "name": "University of Maryland, College Park", "city": "College Park", "location": "Maryland", "rating": "4.2"},
    {"id": 29, "name": "University of Pittsburgh", "city": "Pittsburgh", "location": "Pennsylvania", "rating": "4.2"},
    {"id": 30, "name": "University of North Carolina at Chapel Hill", "city": "Chapel Hill", "location": "North Carolina", "rating": "4.2"},
    {"id": 31, "name": "University of Minnesota", "city": "Minneapolis", "location": "Minnesota", "rating": "4.2"},
    {"id": 32, "name": "University of California, Riverside", "city": "Riverside", "location": "California", "rating": "4.1"},
    {"id": 33, "name": "University of Arizona", "city": "Tucson", "location": "Arizona", "rating": "4.1"},
    {"id": 34, "name": "University of Colorado Boulder", "city": "Boulder", "location": "Colorado", "rating": "4.1"},
    {"id": 35, "name": "University of Miami", "city": "Coral Gables", "location": "Florida", "rating": "4.1"},
    {"id": 36, "name": "University of Georgia", "city": "Athens", "location": "Georgia", "rating": "4.0"},
    {"id": 37, "name": "University of Iowa", "city": "Iowa City", "location": "Iowa", "rating": "4.0"},
    {"id": 38, "name": "University of Oregon", "city": "Eugene", "location": "Oregon", "rating": "4.0"},
    {"id": 39, "name": "University of Kansas", "city": "Lawrence", "location": "Kansas", "rating": "4.0"},
    {"id": 40, "name": "University of Nebraska-Lincoln", "city": "Lincoln", "location": "Nebraska", "rating": "4.0"},
    {"id": 41, "name": "University of Utah", "city": "Salt Lake City", "location": "Utah", "rating": "4.0"},
    {"id": 42, "name": "University of Alabama", "city": "Tuscaloosa", "location": "Alabama", "rating": "4.0"},
    {"id": 43, "name": "University of Tennessee", "city": "Knoxville", "location": "Tennessee", "rating": "4.0"},
    {"id": 44, "name": "University of Oklahoma", "city": "Norman", "location": "Oklahoma", "rating": "4.0"},
    {"id": 45, "name": "University of South Carolina", "city": "Columbia", "location": "South Carolina", "rating": "4.0"},
    {"id": 46, "name": "University of Mississippi", "city": "University", "location": "Mississippi", "rating": "4.0"},
    {"id": 47, "name": "University of Arkansas", "city": "Fayetteville", "location": "Arkansas", "rating": "4.0"},
    {"id": 48, "name": "University of Nevada, Reno", "city": "Reno", "location": "Nevada", "rating": "4.0"},
    {"id": 49, "name": "University of Washington, Seattle", "city": "Seattle", "location": "Washington", "rating": "4.0"},
    {"id": 50, "name": "University of Hawaii at Manoa", "city": "Honolulu", "location": "Hawaii", "rating": "4.0"},
    {"id": 51, "name": "University of New Mexico", "city": "Albuquerque", "location": "New Mexico", "rating": "4.0"},
    {"id": 52, "name": "University of Rhode Island", "city": "Kingston", "location": "Rhode Island", "rating": "4.0"},
    {"id": 53, "name": "University of Vermont", "city": "Burlington", "location": "Vermont", "rating": "4.0"},
    {"id": 54, "name": "University of Connecticut", "city": "Storrs", "location": "Connecticut", "rating": "4.0"},
    {"id": 55, "name": "University of Maine", "city": "Orono", "location": "Maine", "rating": "4.0"},
    {"id": 56, "name": "University of North Dakota", "city": "Grand Forks", "location": "North Dakota", "rating": "4.0"},
    {"id": 57, "name": "University of South Dakota", "city": "Vermillion", "location": "South Dakota", "rating": "4.0"},
    {"id": 58, "name": "University of West Virginia", "city": "Morgantown", "location": "West Virginia", "rating": "4.0"},
    {"id": 59, "name": "University of Wyoming", "city": "Laramie", "location": "Wyoming", "rating": "4.0"},
    {"id": 60, "name": "American University", "city": "Washington", "location": "District of Columbia", "rating": "4.0"},
    {"id": 61, "name": "Boston College", "city": "Chestnut Hill", "location": "Massachusetts", "rating": "4.1"},
    {"id": 62, "name": "University of Denver", "city": "Denver", "location": "Colorado", "rating": "4.0"},
    {"id": 63, "name": "Tulane University", "city": "New Orleans", "location": "Louisiana", "rating": "4.1"},
    {"id": 64, "name": "Wake Forest University", "city": "Winston-Salem", "location": "North Carolina", "rating": "4.1"},
    {"id": 65, "name": "Emory University", "city": "Atlanta", "location": "Georgia", "rating": "4.2"},
    {"id": 66, "name": "University of Richmond", "city": "Richmond", "location": "Virginia", "rating": "4.2"},
    {"id": 67, "name": "Vanderbilt University", "city": "Nashville", "location": "Tennessee", "rating": "4.3"},
    {"id": 68, "name": "George Washington University", "city": "Washington", "location": "District of Columbia", "rating": "4.2"},
    {"id": 69, "name": "Claremont McKenna College", "city": "Claremont", "location": "California", "rating": "4.3"},
    {"id": 70, "name": "Pomona College", "city": "Claremont", "location": "California", "rating": "4.4"},
    {"id": 71, "name": "Harvey Mudd College", "city": "Claremont", "location": "California", "rating": "4.5"},
    {"id": 72, "name": "Scripps College", "city": "Claremont", "location": "California", "rating": "4.3"},
    {"id": 73, "name": "Pitzer College", "city": "Claremont", "location": "California", "rating": "4.2"},
    {"id": 74, "name": "Swarthmore College", "city": "Swarthmore", "location": "Pennsylvania", "rating": "4.4"},
    {"id": 75, "name": "Wellesley College", "city": "Wellesley", "location": "Massachusetts", "rating": "4.4"},
    {"id": 76, "name": "Smith College", "city": "Northampton", "location": "Massachusetts", "rating": "4.4"},
    {"id": 77, "name": "Bryn Mawr College", "city": "Bryn Mawr", "location": "Pennsylvania", "rating": "4.3"},
    {"id": 78, "name": "Mount Holyoke College", "city": "South Hadley", "location": "Massachusetts", "rating": "4.2"},
    {"id": 79, "name": "The College of William & Mary", "city": "Williamsburg", "location": "Virginia", "rating": "4.3"},
    {"id": 80, "name": "Skidmore College", "city": "Saratoga Springs", "location": "New York", "rating": "4.2"},
    {"id": 81, "name": "Hamilton College", "city": "Clinton", "location": "New York", "rating": "4.3"},
    {"id": 82, "name": "Colgate University", "city": "Hamilton", "location": "New York", "rating": "4.4"},
    {"id": 83, "name": "Vassar College", "city": "Poughkeepsie", "location": "New York", "rating": "4.3"},
    {"id": 84, "name": "Wesleyan University", "city": "Middletown", "location": "Connecticut", "rating": "4.4"},
    {"id": 85, "name": "Oberlin College", "city": "Oberlin", "location": "Ohio", "rating": "4.2"},
    {"id": 86, "name": "Kenyon College", "city": "Gambier", "location": "Ohio", "rating": "4.3"},
    {"id": 87, "name": "Carleton College", "city": "Northfield", "location": "Minnesota", "rating": "4.4"},
    {"id": 88, "name": "Macalester College", "city": "St. Paul", "location": "Minnesota", "rating": "4.3"},
    {"id": 89, "name": "Grinnell College", "city": "Grinnell", "location": "Iowa", "rating": "4.2"},
    {"id": 90, "name": "Bates College", "city": "Lewiston", "location": "Maine", "rating": "4.1"},
    {"id": 91, "name": "Bowdoin College", "city": "Brunswick", "location": "Maine", "rating": "4.3"},
    {"id": 92, "name": "Middlebury College", "city": "Middlebury", "location": "Vermont", "rating": "4.4"},
    {"id": 93, "name": "Haverford College", "city": "Haverford", "location": "Pennsylvania", "rating": "4.3"},
    {"id": 94, "name": "Swarthmore College", "city": "Swarthmore", "location": "Pennsylvania", "rating": "4.4"},
    {"id": 95, "name": "University of Chicago", "city": "Chicago", "location": "Illinois", "rating": "4.7"},
    {"id": 96, "name": "Dartmouth College", "city": "Hanover", "location": "New Hampshire", "rating": "4.5"},
    {"id": 97, "name": "University of California, Los Angeles", "city": "Los Angeles", "location": "California", "rating": "4.5"},
    {"id": 98, "name": "University of Southern California", "city": "Los Angeles", "location": "California", "rating": "4.4"},
    {"id": 99, "name": "University of Virginia", "city": "Charlottesville", "location": "Virginia", "rating": "4.5"},
    {"id": 100, "name": "University of Pennsylvania", "city": "Philadelphia", "location": "Pennsylvania", "rating": "4.6"},
    {"id": 101, "name": "Georgetown University", "city": "Washington", "location": "District of Columbia", "rating": "4.4"},
    {"id": 102, "name": "University of North Carolina at Chapel Hill", "city": "Chapel Hill", "location": "North Carolina", "rating": "4.3"},
    {"id": 103, "name": "University of Michigan", "city": "Ann Arbor", "location": "Michigan", "rating": "4.5"},
    {"id": 104, "name": "University of California, Berkeley", "city": "Berkeley", "location": "California", "rating": "4.5"},
    {"id": 105, "name": "University of Texas at Austin", "city": "Austin", "location": "Texas", "rating": "4.3"},
    {"id": 106, "name": "University of California, Davis", "city": "Davis", "location": "California", "rating": "4.2"},
    {"id": 107, "name": "University of Wisconsin-Madison", "city": "Madison", "location": "Wisconsin", "rating": "4.2"},
    {"id": 108, "name": "University of Florida", "city": "Gainesville", "location": "Florida", "rating": "4.1"},
    {"id": 109, "name": "University of Illinois at Urbana-Champaign", "city": "Champaign", "location": "Illinois", "rating": "4.2"},
    {"id": 110, "name": "University of Washington", "city": "Seattle", "location": "Washington", "rating": "4.3"},
    {"id": 111, "name": "University of Maryland, College Park", "city": "College Park", "location": "Maryland", "rating": "4.2"},
    {"id": 112, "name": "University of Iowa", "city": "Iowa City", "location": "Iowa", "rating": "4.0"},
    {"id": 113, "name": "University of Colorado Boulder", "city": "Boulder", "location": "Colorado", "rating": "4.1"},
    {"id": 114, "name": "University of Arizona", "city": "Tucson", "location": "Arizona", "rating": "4.1"},
    {"id": 115, "name": "University of Miami", "city": "Coral Gables", "location": "Florida", "rating": "4.1"},
    {"id": 116, "name": "University of Oregon", "city": "Eugene", "location": "Oregon", "rating": "4.0"},
    {"id": 117, "name": "University of Georgia", "city": "Athens", "location": "Georgia", "rating": "4.1"},
    {"id": 118, "name": "University of Alabama", "city": "Tuscaloosa", "location": "Alabama", "rating": "4.0"},
    {"id": 119, "name": "University of South Carolina", "city": "Columbia", "location": "South Carolina", "rating": "4.1"},
    {"id": 120, "name": "University of Tennessee", "city": "Knoxville", "location": "Tennessee", "rating": "4.0"},
    {"id": 121, "name": "University of Oklahoma", "city": "Norman", "location": "Oklahoma", "rating": "4.0"},
    {"id": 122, "name": "University of Arkansas", "city": "Fayetteville", "location": "Arkansas", "rating": "4.0"},
    {"id": 123, "name": "University of Nevada, Reno", "city": "Reno", "location": "Nevada", "rating": "4.0"},
    {"id": 124, "name": "University of West Virginia", "city": "Morgantown", "location": "West Virginia", "rating": "4.0"},
    {"id": 125, "name": "American University", "city": "Washington", "location": "District of Columbia", "rating": "4.0"},
    {"id": 126, "name": "Boston College", "city": "Chestnut Hill", "location": "Massachusetts", "rating": "4.1"},
    {"id": 127, "name": "Tulane University", "city": "New Orleans", "location": "Louisiana", "rating": "4.1"},
    {"id": 128, "name": "Wake Forest University", "city": "Winston-Salem", "location": "North Carolina", "rating": "4.1"},
    {"id": 129, "name": "Emory University", "city": "Atlanta", "location": "Georgia", "rating": "4.2"},
    {"id": 130, "name": "University of Richmond", "city": "Richmond", "location": "Virginia", "rating": "4.2"},
    {"id": 131, "name": "Vanderbilt University", "city": "Nashville", "location": "Tennessee", "rating": "4.3"},
    {"id": 132, "name": "George Washington University", "city": "Washington", "location": "District of Columbia", "rating": "4.2"},
    {"id": 133, "name": "Claremont McKenna College", "city": "Claremont", "location": "California", "rating": "4.3"},
    {"id": 134, "name": "Pomona College", "city": "Claremont", "location": "California", "rating": "4.4"},
    {"id": 135, "name": "Harvey Mudd College", "city": "Claremont", "location": "California", "rating": "4.5"},
    {"id": 136, "name": "Scripps College", "city": "Claremont", "location": "California", "rating": "4.3"},
    {"id": 137, "name": "Pitzer College", "city": "Claremont", "location": "California", "rating": "4.2"},
    {"id": 138, "name": "Swarthmore College", "city": "Swarthmore", "location": "Pennsylvania", "rating": "4.4"},
    {"id": 139, "name": "Wellesley College", "city": "Wellesley", "location": "Massachusetts", "rating": "4.4"},
    {"id": 140, "name": "Smith College", "city": "Northampton", "location": "Massachusetts", "rating": "4.4"},
    {"id": 141, "name": "Bryn Mawr College", "city": "Bryn Mawr", "location": "Pennsylvania", "rating": "4.3"},
    {"id": 142, "name": "Mount Holyoke College", "city": "South Hadley", "location": "Massachusetts", "rating": "4.2"},
    {"id": 143, "name": "The College of William & Mary", "city": "Williamsburg", "location": "Virginia", "rating": "4.3"},
    {"id": 144, "name": "Skidmore College", "city": "Saratoga Springs", "location": "New York", "rating": "4.2"},
    {"id": 145, "name": "Hamilton College", "city": "Clinton", "location": "New York", "rating": "4.3"},
    {"id": 146, "name": "Colgate University", "city": "Hamilton", "location": "New York", "rating": "4.4"},
    {"id": 147, "name": "Vassar College", "city": "Poughkeepsie", "location": "New York", "rating": "4.3"},
    {"id": 148, "name": "Wesleyan University", "city": "Middletown", "location": "Connecticut", "rating": "4.4"},
    {"id": 149, "name": "Oberlin College", "city": "Oberlin", "location": "Ohio", "rating": "4.2"},
    {"id": 150, "name": "Kenyon College", "city": "Gambier", "location": "Ohio", "rating": "4.3"},
    {"id": 151, "name": "Carleton College", "city": "Northfield", "location": "Minnesota", "rating": "4.4"},
    {"id": 152, "name": "Macalester College", "city": "St. Paul", "location": "Minnesota", "rating": "4.3"},
    {"id": 153, "name": "Grinnell College", "city": "Grinnell", "location": "Iowa", "rating": "4.2"},
    {"id": 154, "name": "Bates College", "city": "Lewiston", "location": "Maine", "rating": "4.1"},
    {"id": 155, "name": "Bowdoin College", "city": "Brunswick", "location": "Maine", "rating": "4.3"},
    {"id": 156, "name": "Middlebury College", "city": "Middlebury", "location": "Vermont", "rating": "4.4"},
    {"id": 157, "name": "Haverford College", "city": "Haverford", "location": "Pennsylvania", "rating": "4.3"},
    {"id": 158, "name": "Swarthmore College", "city": "Swarthmore", "location": "Pennsylvania", "rating": "4.4"},
    {"id": 159, "name": "University of Chicago", "city": "Chicago", "location": "Illinois", "rating": "4.7"},
    {"id": 160, "name": "Dartmouth College", "city": "Hanover", "location": "New Hampshire", "rating": "4.5"},
    {"id": 161, "name": "University of California, Los Angeles", "city": "Los Angeles", "location": "California", "rating": "4.5"},
    {"id": 162, "name": "University of Southern California", "city": "Los Angeles", "location": "California", "rating": "4.4"},
    {"id": 163, "name": "University of Virginia", "city": "Charlottesville", "location": "Virginia", "rating": "4.5"},
    {"id": 164, "name": "University of Pennsylvania", "city": "Philadelphia", "location": "Pennsylvania", "rating": "4.6"},
    {"id": 165, "name": "Georgetown University", "city": "Washington", "location": "District of Columbia", "rating": "4.4"},
    {"id": 166, "name": "University of North Carolina at Chapel Hill", "city": "Chapel Hill", "location": "North Carolina", "rating": "4.3"},
    {"id": 167, "name": "University of Michigan", "city": "Ann Arbor", "location": "Michigan", "rating": "4.5"},
    {"id": 168, "name": "University of California, Berkeley", "city": "Berkeley", "location": "California", "rating": "4.5"},
    {"id": 169, "name": "University of Texas at Austin", "city": "Austin", "location": "Texas", "rating": "4.3"},
    {"id": 170, "name": "University of California, Davis", "city": "Davis", "location": "California", "rating": "4.2"},
    {"id": 171, "name": "University of Wisconsin-Madison", "city": "Madison", "location": "Wisconsin", "rating": "4.2"},
    {"id": 172, "name": "University of Florida", "city": "Gainesville", "location": "Florida", "rating": "4.1"},
    {"id": 173, "name": "University of Illinois at Urbana-Champaign", "city": "Champaign", "location": "Illinois", "rating": "4.2"},
    {"id": 174, "name": "University of Washington", "city": "Seattle", "location": "Washington", "rating": "4.3"},
    {"id": 175, "name": "University of Maryland, College Park", "city": "College Park", "location": "Maryland", "rating": "4.2"},
    {"id": 176, "name": "University of Iowa", "city": "Iowa City", "location": "Iowa", "rating": "4.0"},
    {"id": 177, "name": "University of Colorado Boulder", "city": "Boulder", "location": "Colorado", "rating": "4.1"},
    {"id": 178, "name": "University of Arizona", "city": "Tucson", "location": "Arizona", "rating": "4.1"},
    {"id": 179, "name": "University of Miami", "city": "Coral Gables", "location": "Florida", "rating": "4.1"},
    {"id": 180, "name": "University of Oregon", "city": "Eugene", "location": "Oregon", "rating": "4.0"},
    {"id": 181, "name": "University of Georgia", "city": "Athens", "location": "Georgia", "rating": "4.1"},
    {"id": 182, "name": "University of Alabama", "city": "Tuscaloosa", "location": "Alabama", "rating": "4.0"},
    {"id": 183, "name": "University of South Carolina", "city": "Columbia", "location": "South Carolina", "rating": "4.1"},
    {"id": 184, "name": "University of Tennessee", "city": "Knoxville", "location": "Tennessee", "rating": "4.0"},
    {"id": 185, "name": "University of Oklahoma", "city": "Norman", "location": "Oklahoma", "rating": "4.0"},
    {"id": 186, "name": "University of Arkansas", "city": "Fayetteville", "location": "Arkansas", "rating": "4.0"},
    {"id": 187, "name": "University of Nevada, Reno", "city": "Reno", "location": "Nevada", "rating": "4.0"},
    {"id": 188, "name": "University of West Virginia", "city": "Morgantown", "location": "West Virginia", "rating": "4.0"},
    {"id": 189, "name": "American University", "city": "Washington", "location": "District of Columbia", "rating": "4.0"},
    {"id": 190, "name": "Boston College", "city": "Chestnut Hill", "location": "Massachusetts", "rating": "4.1"},
    {"id": 191, "name": "Tulane University", "city": "New Orleans", "location": "Louisiana", "rating": "4.1"},
    {"id": 192, "name": "Wake Forest University", "city": "Winston-Salem", "location": "North Carolina", "rating": "4.1"},
    {"id": 193, "name": "Emory University", "city": "Atlanta", "location": "Georgia", "rating": "4.2"},
    {"id": 194, "name": "University of Richmond", "city": "Richmond", "location": "Virginia", "rating": "4.2"},
    {"id": 195, "name": "Vanderbilt University", "city": "Nashville", "location": "Tennessee", "rating": "4.3"},
    {"id": 196, "name": "George Washington University", "city": "Washington", "location": "District of Columbia", "rating": "4.2"},
    {"id": 197, "name": "Claremont McKenna College", "city": "Claremont", "location": "California", "rating": "4.3"},
    {"id": 198, "name": "Pomona College", "city": "Claremont", "location": "California", "rating": "4.4"},
    {"id": 199, "name": "Harvey Mudd College", "city": "Claremont", "location": "California", "rating": "4.5"},
    {"id": 200, "name": "Scripps College", "city": "Claremont", "location": "California", "rating": "4.3"},
    {"id": 201, "name": "Pitzer College", "city": "Claremont", "location": "California", "rating": "4.2"},
    {"id": 202, "name": "Swarthmore College", "city": "Swarthmore", "location": "Pennsylvania", "rating": "4.4"},
    {"id": 203, "name": "Wellesley College", "city": "Wellesley", "location": "Massachusetts", "rating": "4.4"},
    {"id": 204, "name": "Smith College", "city": "Northampton", "location": "Massachusetts", "rating": "4.4"},
    {"id": 205, "name": "Bryn Mawr College", "city": "Bryn Mawr", "location": "Pennsylvania", "rating": "4.3"},
    {"id": 206, "name": "Mount Holyoke College", "city": "South Hadley", "location": "Massachusetts", "rating": "4.2"},
    {"id": 207, "name": "The College of William & Mary", "city": "Williamsburg", "location": "Virginia", "rating": "4.3"},
    {"id": 208, "name": "Skidmore College", "city": "Saratoga Springs", "location": "New York", "rating": "4.2"},
    {"id": 209, "name": "Hamilton College", "city": "Clinton", "location": "New York", "rating": "4.3"},
    {"id": 210, "name": "Colgate University", "city": "Hamilton", "location": "New York", "rating": "4.4"},
    {"id": 211, "name": "Vassar College", "city": "Poughkeepsie", "location": "New York", "rating": "4.3"},
    {"id": 212, "name": "Wesleyan University", "city": "Middletown", "location": "Connecticut", "rating": "4.4"},
    {"id": 213, "name": "Oberlin College", "city": "Oberlin", "location": "Ohio", "rating": "4.2"},
    {"id": 214, "name": "Kenyon College", "city": "Gambier", "location": "Ohio", "rating": "4.3"},
    {"id": 215, "name": "Carleton College", "city": "Northfield", "location": "Minnesota", "rating": "4.4"},
    {"id": 216, "name": "Macalester College", "city": "St. Paul", "location": "Minnesota", "rating": "4.3"},
    {"id": 217, "name": "Grinnell College", "city": "Grinnell", "location": "Iowa", "rating": "4.2"},
    {"id": 218, "name": "Bates College", "city": "Lewiston", "location": "Maine", "rating": "4.1"},
    {"id": 219, "name": "Bowdoin College", "city": "Brunswick", "location": "Maine", "rating": "4.3"},
    {"id": 220, "name": "Middlebury College", "city": "Middlebury", "location": "Vermont", "rating": "4.4"},
    {"id": 221, "name": "Haverford College", "city": "Haverford", "location": "Pennsylvania", "rating": "4.3"},
    {"id": 222, "name": "Swarthmore College", "city": "Swarthmore", "location": "Pennsylvania", "rating": "4.4"}
]

module.exports={School,College}