#According to the 2024 seaso
DRIVERS = [
    {'id': 1, 'name': 'Lewis Hamilton', 'team': 'Mercedes'},
    {'id': 2, 'name': 'George Russell', 'team': 'Mercedes'},
    {'id': 3, 'name': 'Max Verstappen', 'team': 'Red Bull Racing'},
    {'id': 4, 'name': 'Sergio Perez', 'team': 'Red Bull Racing'},
    {'id': 5, 'name': 'Charles Leclerc', 'team': 'Ferrari'},
    {'id': 6, 'name': 'Carlos Sainz', 'team': 'Ferrari'},
    {'id': 7, 'name': 'Lando Norris', 'team': 'McLaren'},
    {'id': 8, 'name': 'Oscar Piastri', 'team': 'McLaren'},
    {'id': 9, 'name': 'Fernando Alonso', 'team': 'Aston Martin'},
    {'id': 10, 'name': 'Lance Stroll', 'team': 'Aston Martin'},
    {'id': 11, 'name': 'Esteban Ocon', 'team': 'Alpine'},
    {'id': 12, 'name': 'Pierre Gasly', 'team': 'Alpine'},
    {'id': 13, 'name': 'Valtteri Bottas', 'team': 'Alfa Romeo'},
    {'id': 14, 'name': 'Guanyu Zhou', 'team': 'Alfa Romeo'},
    {'id': 15, 'name': 'Kevin Magnussen', 'team': 'Haas'},
    {'id': 16, 'name': 'Nico Hulkenberg', 'team': 'Haas'},
    {'id': 17, 'name': 'Yuki Tsunoda', 'team': 'AlphaTauri'},
    {'id': 18, 'name': 'Nyck de Vries', 'team': 'AlphaTauri'},
    {'id': 19, 'name': 'Alexander Albon', 'team': 'Williams'},
    {'id': 20, 'name': 'Logan Sargeant', 'team': 'Williams'},
]

TEAMS = [
    {'id': 1, 'name': 'Mercedes', 'principal': 'Toto Wolff'},
    {'id': 2, 'name': 'Red Bull Racing', 'principal': 'Christian Horner'},
    {'id': 3, 'name': 'Ferrari', 'principal': 'Fred Vasseur'},
    {'id': 4, 'name': 'McLaren', 'principal': 'Andrea Stella'},
    {'id': 5, 'name': 'Aston Martin', 'principal': 'Mike Krack'},
    {'id': 6, 'name': 'Alpine', 'principal': 'Laurent Rossi'},
    {'id': 7, 'name': 'Alfa Romeo', 'principal': 'Alessandro Alunni Bravi'},
    {'id': 8, 'name': 'Haas', 'principal': 'Guenther Steiner'},
    {'id': 9, 'name': 'AlphaTauri', 'principal': 'Franz Tost'},
    {'id': 10, 'name': 'Williams', 'principal': 'James Vowles'},
]

RACES = [
    {'id': 1, 'name': 'Bahrain Grand Prix', 'location': 'Sakhir'},
    {'id': 2, 'name': 'Saudi Arabian Grand Prix', 'location': 'Jeddah'},
    {'id': 3, 'name': 'Australian Grand Prix', 'location': 'Melbourne'},
    {'id': 4, 'name': 'Azerbaijan Grand Prix', 'location': 'Baku'},
    {'id': 5, 'name': 'Miami Grand Prix', 'location': 'Miami'},
    {'id': 6, 'name': 'Emilia Romagna Grand Prix', 'location': 'Imola'},
    {'id': 7, 'name': 'Monaco Grand Prix', 'location': 'Monte Carlo'},
    {'id': 8, 'name': 'Spanish Grand Prix', 'location': 'Barcelona'},
    {'id': 9, 'name': 'Canadian Grand Prix', 'location': 'Montreal'},
    {'id': 10, 'name': 'Austrian Grand Prix', 'location': 'Spielberg'},
    {'id': 11, 'name': 'British Grand Prix', 'location': 'Silverstone'},
    {'id': 12, 'name': 'Hungarian Grand Prix', 'location': 'Budapest'},
    {'id': 13, 'name': 'Belgian Grand Prix', 'location': 'Spa-Francorchamps'},
    {'id': 14, 'name': 'Dutch Grand Prix', 'location': 'Zandvoort'},
    {'id': 15, 'name': 'Italian Grand Prix', 'location': 'Monza'},
    {'id': 16, 'name': 'Singapore Grand Prix', 'location': 'Singapore'},
    {'id': 17, 'name': 'Japanese Grand Prix', 'location': 'Suzuka'},
    {'id': 18, 'name': 'Qatar Grand Prix', 'location': 'Lusail'},
    {'id': 19, 'name': 'United States Grand Prix', 'location': 'Austin'},
    {'id': 20, 'name': 'Mexican Grand Prix', 'location': 'Mexico City'},
    {'id': 21, 'name': 'Brazilian Grand Prix', 'location': 'Sao Paulo'},
    {'id': 22, 'name': 'Las Vegas Grand Prix', 'location': 'Las Vegas'},
    {'id': 23, 'name': 'Abu Dhabi Grand Prix', 'location': 'Yas Marina'},
]
